# Generated by Django 4.0.4 on 2022-06-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_groupmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmodel',
            name='gp_behaves_like_sub_ledger',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='nett_debit_credit_bal_reporting',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='used_for_calculation',
            field=models.CharField(max_length=225),
        ),
    ]
