# Generated by Django 4.0.4 on 2022-06-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_groupmodel_gp_behaves_like_sub_ledger_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=225)),
                ('formal_name', models.CharField(max_length=225)),
                ('ISO_code', models.CharField(max_length=225)),
                ('decimal_places', models.CharField(default=2, max_length=225)),
                ('show_in_millions', models.CharField(max_length=225)),
                ('suffix_to_amount', models.CharField(max_length=225)),
                ('space_symbol_amount', models.CharField(max_length=225)),
                ('word_after_decimal', models.CharField(max_length=225)),
                ('decimal_no_in_words', models.CharField(max_length=225)),
                ('flag', models.CharField(default=0, max_length=225)),
            ],
        ),
    ]
