# Generated by Django 4.0.4 on 2022-07-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_ledger_vouchermodels_ledger_tax_register_ledger_tax_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockgroupcreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225)),
                ('under', models.CharField(max_length=225)),
                ('Should_quantties_of_items_be_added', models.CharField(max_length=225)),
                ('Set_or_Alter_GST_Details', models.CharField(max_length=225)),
            ],
        ),
    ]
