# Generated by Django 4.0.4 on 2022-07-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_create_stockcate_create_stockgrp_create_stockitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_goddown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225)),
                ('under', models.CharField(max_length=225)),
            ],
        ),
    ]
