# Generated by Django 4.0.4 on 2022-07-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_createcurrency_flag_currencyalter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Godowns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225)),
                ('godown', models.CharField(max_length=225)),
            ],
        ),
        migrations.DeleteModel(
            name='create_goddown',
        ),
    ]
